### ISSUE TITLE
Possibility to enable Steam Achievements

### ISSUE THREAD

**Issue by Merkury90** [PhantomGamers/DSPAchievementsEnabler#1]
Hello.

I have found this mod after my clean savefile (no mods, 30h in) got corrupted somehow and disabled possibility to get achievements. I believe it has happened due to me using some of the old blueprints because that is everything that changed in my game in last 10 hours.

Would it be possible to bring back functionality to enable Steam achievemenets? Or maybe make it as an option inside a mod?

Best regards!

**Comment by PhantomGamers** [comment]
If you compile the plugin with these lines commented out you will be able to unlock Steam achievements https://github.com/PhantomGamers/DSPAchievementsEnabler/blob/d614fa617ed4d889345291bf2930254dd5a46d4d/Plugin.cs#L36

I may at some point include this as a config option but I wanted to try to make this without pissing off the game devs... though I don't think their time spent protecting Steam achievements is worth it given the fact that things like SAM exist https://github.com/gibbed/SteamAchievementManager

Also there is an issue with how the game handles achievements, so if you unlock achievements while using this mod and then uninstall the mod you will unlock them on Steam

**Comment by PhantomGamers** [comment]
There is now a config entry to enable platform achievements
