### ISSUE TITLE
Latest update broke mod

### ISSUE THREAD

**Issue by heliostellar** [PhantomGamers/DSPAchievementsEnabler#3]
^Title. Getting a red console error with the mod. After disabling it, the error is gone.

**Comment by PhantomGamers** [comment]
What is the error? What are you doing when the error occurs? I cannot fix errors that I am not aware of. I'm not getting any errors on my end.

**Comment by heliostellar** [comment]
I had started a new game. When I go back into the save though, the error is gone. Maybe there was just a hiccup on my end.
